### ISSUE TITLE
Replace the mocked Ajax request with request to real server

### ISSUE THREAD

**Issue by ipeychev** [wedeploy/wedeploy-sdk-js#145]
Currently for testing Ajax requests there are two mocked requests object - one for the [browser](https://github.com/wedeploy/api-js/blob/a12f7191e4461e27bf26cea8f4a5e2acd6055c39/test/fixtures/browser/AjaxRequestMock.js) and another one for [Node](https://github.com/wedeploy/api-js/blob/a12f7191e4461e27bf26cea8f4a5e2acd6055c39/test/fixtures/node/NodeRequestMock.js).
Mocking approach is questionable, hence, we may evaluate to replace mocking with requests to a real server as in [API](https://github.com/wedeploy/api) project.

Here is this task split in several issue to provide better visibility of the work:
- [ ] Convert tests in Data https://github.com/wedeploy/api-js/issues/147
- [ ] Convert tests in Auth https://github.com/wedeploy/api-js/issues/148
- [ ] Convert tests in Email https://github.com/wedeploy/api-js/issues/150
- [ ] Convert tests in WeDeploy https://github.com/wedeploy/api-js/issues/149

**Comment by ipeychev** [comment]
Moving this to backlog since it requires infrastructure changes first.
